<a href="https://colab.research.google.com/github/softwarerbfl/imageProcessing/blob/main/Notebook-Week3/imageProcess220318.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount("/gdrive")

Mounted at /gdrive


In [ ]:
import numpy as np
a=np.array([1,2,3]) #파이썬의 배열을 numpy의 array객체로 변환시켜줌
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


numpy.zeros()

In [ ]:
np.zeros(2) #원하는 개수만큼 0.0(실수임에 주의!)으로 채워 array를 만들어준다

array([0., 0.])

In [ ]:
b=np.zeros(5)
print(b)
print(type(b))

[0. 0. 0. 0. 0.]
<class 'numpy.ndarray'>


numpy.ones()

In [ ]:
np.ones(2)

array([1., 1.])

numpy.empty()

In [ ]:
np.empty(10) #random 숫자로 배열을 인자값의 크기만큼 만든다

array([4.63866555e-310, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000])

numpy.arange()

In [ ]:
np.arange(4) 

array([0, 1, 2, 3])

In [ ]:
np.arange(2,10,2) #(초기값, 마지막값, step 값)

array([2, 4, 6, 8])

In [ ]:
#주어진 구간을 num의 개수만큼 나누어준다
#시작값+(num-1)*x=마지막값 에서 x는 구간의 크기
a=np.linspace(0,10,num=5)
print("a=",a)
b=np.linspace(0,10,num=10)
print("b=",b)

a= [ 0.   2.5  5.   7.5 10. ]
b= [ 0.          1.11111111  2.22222222  3.33333333  4.44444444  5.55555556
  6.66666667  7.77777778  8.88888889 10.        ]


# array의 shape와 크기를 아는 방법
*  ndarray.ndim
*  ndarray.size
*  ndarray.shape

In [ ]:
x=np.arange(24).reshape(3,2,4) #3*2*4의 형태로 변환
print("x=",x)
print()
print("x.ndim = ",x.ndim)
print()
print("x.size = ",x.size)
print()
print("x.shape = ",x.shape)

x= [[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]]]

x.ndim =  3

x.size =  24

x.shape =  (3, 2, 4)


# 1D 배열 슬라이싱, 인덱싱

In [ ]:
x=np.arange(24)
print("x[0]=",x[0])
print("x[1]=",x[1])

x[0]= 0
x[1]= 1


[start:end]

In [ ]:
print("x[1:2]=",x[1:2])
print("x[1:7]=",x[1:7])

X[1:2]= [1]
X[1:7]= [1 2 3 4 5 6]


[start:end:interval]

In [ ]:
print("x[2::3]=",x[2::3])
#[2,5,8,11,14,17,20,23]을 다시 [0:3]만큼 슬라이싱
print("x[2::3][0:3]=",x[2::3][0:3])

x[2::3]= [ 2  5  8 11 14 17 20 23]
x[2::3][0:3]= [2 5 8]


In [ ]:
print("x[::]=",x[::])

x[::]= [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


Negative Indexing

In [ ]:
print("x[-7:] = ",x[-7:])

print("x[-7:2] = ",x[-7:2])

print("x[-7::2] = ",x[-7::2])

print("x[-7::-2] = ",x[-7::-2])

print("x[:-4] = ",x[:-4])

print("x[:-4:-1] = ",x[:-4:-1])

x[-7:] =  [17 18 19 20 21 22 23]
x[-7:2] =  []
x[-7::2] =  [17 19 21 23]
x[-7::-2] =  [17 15 13 11  9  7  5  3  1]
x[:-4] =  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
x[:-4:-1] =  [23 22 21]


# 2D 배열 슬라이싱, 인덱싱

In [ ]:
t = np.arange(42)
print("t = ",t)
y = np.arange(42).reshape(6,7)
print("y = ",y)

t =  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41]
y =  [[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]
 [35 36 37 38 39 40 41]]


In [ ]:
print("y[0]=",y[0])
print("y[1]=",y[1])

y[0]= [0 1 2 3 4 5 6]
y[1]= [ 7  8  9 10 11 12 13]


In [ ]:
#첫 번째 열 출력
print("y[:,0]=",y[:,0])
#세 번째 열 출력
print("y[:,3]=",y[:,3])

y[:,0]= [ 0  7 14 21 28 35]
y[:,3]= [ 3 10 17 24 31 38]


In [ ]:
print("y[2,3]=",y[2,3])

y[2,3]= 17


In [ ]:
#0:3에서 3은 exclusive이므로 첫번째행~세번째행까지만 출력 
print("y[0:3,1]=",y[0:3,1])

y[0:3,1]= [ 1  8 15]


Submatrix

In [ ]:
print("y=",y)
print()
print("y[1:4,0:2]=",y[1:4,0:2])

y= [[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]
 [35 36 37 38 39 40 41]]

y[1:4,0:2]= [[ 7  8]
 [14 15]
 [21 22]]


In [ ]:
#첫번째, 세번째, 다섯번째 행 출력
print("y[0::2]=",y[0::2])

y[0::2]= [[ 0  1  2  3  4  5  6]
 [14 15 16 17 18 19 20]
 [28 29 30 31 32 33 34]]


In [ ]:
#행은 모두, 열은 2칸씩 jump하면서 출력
print("y[:,0::2]=",y[:,0::2])

y[:,0::2]= [[ 0  2  4  6]
 [ 7  9 11 13]
 [14 16 18 20]
 [21 23 25 27]
 [28 30 32 34]
 [35 37 39 41]]


# 3D 배열 슬라이싱, 인덱싱

In [ ]:
#(장,행,열)
x=np.arange(45).reshape(3,3,5)
print(x)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]

 [[30 31 32 33 34]
  [35 36 37 38 39]
  [40 41 42 43 44]]]


In [ ]:
print("x[0]=",x[0])
print()
print("x[2]=",x[2])

x[0]= [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]

x[2]= [[30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]]


In [ ]:
print(x)
print("x[0,1]=",x[0,1]) #첫 번째 장의 두 번째 행 출력
print()
print("x[0][1] = ",x[0][1]) #첫 번째 장의 두 번째 행 출력

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]

 [[30 31 32 33 34]
  [35 36 37 38 39]
  [40 41 42 43 44]]]
x[0,1]= [5 6 7 8 9]

x[0][1] =  [5 6 7 8 9]


In [ ]:
#첫 번째 장의 두 번째 행의 세 번째 열 출력
print("x[0][1][2] = ",x[0][1][2])

x[0][1][2] =  7


In [ ]:
t=x[1:]
print("t=",t)
print()
print("t[0]=",t[0])
print()
print("x[1:][0]=",x[1:][0]) #x의 두 번째+세 번째 장 중에서 첫 번째 장이므로 최종적으로 x의 두 번째 장
print()
print("x[1:,0]=",x[1:,0])#x의 두 번째,세 번째 장의 첫 번째 행 출력 

t= [[[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]

 [[30 31 32 33 34]
  [35 36 37 38 39]
  [40 41 42 43 44]]]

t[0]= [[15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]

x[1:][0]= [[15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]

x[1:,0]= [[15 16 17 18 19]
 [30 31 32 33 34]]


In [ ]:
print(x)
print("x[1:,0:2,1:4]=",x[1:,0:2,1:4])

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]

 [[30 31 32 33 34]
  [35 36 37 38 39]
  [40 41 42 43 44]]]
x[1:,0:2,1:4]= [[[16 17 18]
  [21 22 23]]

 [[31 32 33]
  [36 37 38]]]
